/* GENERATED by demo/build_sales_data.py — do not hand-edit.
   100% synthetic. No real customer, distributor, product or
   figure appears in this file. Seed 20260816, so regenerating gives
   byte-identical output. */
window.DEMO_MARGIN = {
  "meta": {
    "synthetic": true,
    "currency": "USD",
    "periodLabel": "This year, January to October",
    "seed": 20260816,
    "note": "Every figure on this page is generated. No real customer, distributor, product or number appears anywhere in it."
  },
  "base": {
    "cartons": 347935,
    "revenue": 5690535.95,
    "cogs": 3965238.85,
    "grossProfit": 1725297.1,
    "marginPct": 30.3
  },
  "products": [
    {
      "sku": "Solara Sunflower Oil 1.8L",
      "brand": "Solara",
      "category": "Edible oil",
      "cartons": 51711,
      "price": 22.4,
      "cost": 17.7,
      "revenue": 1158326.4,
      "cogs": 915284.7,
      "grossProfit": 243041.7,
      "marginPct": 21.0,
      "mixPct": 20.4
    },
    {
      "sku": "Solara Sunflower Oil 5L",
      "brand": "Solara",
      "category": "Edible oil",
      "cartons": 17828,
      "price": 54.0,
      "cost": 42.66,
      "revenue": 962712.0,
      "cogs": 760542.48,
      "grossProfit": 202169.52,
      "marginPct": 21.0,
      "mixPct": 16.9
    },
    {
      "sku": "Nuvora Detergent 2kg",
      "brand": "Nuvora",
      "category": "Home care",
      "cartons": 24700,
      "price": 26.3,
      "cost": 17.62,
      "revenue": 649610.0,
      "cogs": 435214.0,
      "grossProfit": 214396.0,
      "marginPct": 33.0,
      "mixPct": 11.4
    },
    {
      "sku": "Amberleaf Black Tea 250g",
      "brand": "Amberleaf",
      "category": "Hot drinks",
      "cartons": 34192,
      "price": 18.75,
      "cost": 10.5,
      "revenue": 641100.0,
      "cogs": 359016.0,
      "grossProfit": 282084.0,
      "marginPct": 44.0,
      "mixPct": 11.3
    },
    {
      "sku": "Crispa Cream Biscuit 90g",
      "brand": "Crispa",
      "category": "Biscuits",
      "cartons": 53134,
      "price": 9.6,
      "cost": 6.05,
      "revenue": 510086.4,
      "cogs": 321460.7,
      "grossProfit": 188625.7,
      "marginPct": 37.0,
      "mixPct": 9.0
    },
    {
      "sku": "Nuvora Dish Liquid 750ml",
      "brand": "Nuvora",
      "category": "Home care",
      "cartons": 39493,
      "price": 11.85,
      "cost": 7.94,
      "revenue": 467992.05,
      "cogs": 313574.42,
      "grossProfit": 154417.63,
      "marginPct": 33.0,
      "mixPct": 8.2
    },
    {
      "sku": "Crispa Wafer Multipack",
      "brand": "Crispa",
      "category": "Biscuits",
      "cartons": 31516,
      "price": 14.1,
      "cost": 8.88,
      "revenue": 444375.6,
      "cogs": 279862.08,
      "grossProfit": 164513.52,
      "marginPct": 37.0,
      "mixPct": 7.8
    },
    {
      "sku": "Pellara Tomato Paste 400g",
      "brand": "Pellara",
      "category": "Ambient",
      "cartons": 51984,
      "price": 8.4,
      "cost": 6.8,
      "revenue": 436665.6,
      "cogs": 353491.2,
      "grossProfit": 83174.4,
      "marginPct": 19.0,
      "mixPct": 7.7
    },
    {
      "sku": "Amberleaf Green Tea 100g",
      "brand": "Amberleaf",
      "category": "Hot drinks",
      "cartons": 14327,
      "price": 15.2,
      "cost": 8.51,
      "revenue": 217770.4,
      "cogs": 121922.77,
      "grossProfit": 95847.63,
      "marginPct": 44.0,
      "mixPct": 3.8
    },
    {
      "sku": "Marisol Bath Soap 125g",
      "brand": "Marisol",
      "category": "Personal",
      "cartons": 29050,
      "price": 6.95,
      "cost": 3.61,
      "revenue": 201897.5,
      "cogs": 104870.5,
      "grossProfit": 97027.0,
      "marginPct": 48.1,
      "mixPct": 3.5
    }
  ],
  "whatIf": {
    "defaultSku": "Solara Sunflower Oil 1.8L",
    "maxPushPct": 40,
    "stepPct": 1,
    "discountPerPushPct": 0.35
  }
};
