/* GENERATED by demo/build_sales_data.py — do not hand-edit.
   100% synthetic. No real customer, distributor, product or
   figure appears in this file. Seed 20260816, so regenerating gives
   byte-identical output. */
window.DEMO_SALES = {
  "meta": {
    "synthetic": true,
    "currency": "USD",
    "currentLabel": "This year",
    "priorLabel": "Last year",
    "throughMonth": "Oct",
    "monthsElapsed": 10,
    "months": [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    ],
    "seed": 20260816,
    "note": "Every figure on this page is generated. No real customer, distributor, product or number appears anywhere in it."
  },
  "kpi": {
    "value": {
      "current": 5690535.95,
      "prior": 5105924.4
    },
    "volume": {
      "current": 347935,
      "prior": 320674
    },
    "lines": {
      "current": 50,
      "prior": 50
    },
    "coverage": {
      "current": 73.6,
      "prior": 74.1
    },
    "dropSize": {
      "current": 16.36,
      "prior": 15.92
    }
  },
  "trend": {
    "value": {
      "current": [
        569174.65,
        550899.85,
        561114.25,
        590293.1,
        613035.65,
        535332.0,
        510082.1,
        541450.05,
        586293.8,
        632860.5
      ],
      "prior": [
        518700.1,
        491774.95,
        515288.4,
        536013.95,
        548838.15,
        480439.8,
        457652.25,
        484367.95,
        517665.45,
        555183.4,
        572669.05,
        599608.25
      ]
    },
    "volume": {
      "current": [
        35255,
        33762,
        34924,
        36089,
        37422,
        32714,
        30943,
        32935,
        35663,
        38228
      ],
      "prior": [
        32850,
        31173,
        32542,
        33709,
        34878,
        30217,
        28599,
        29991,
        32062,
        34653,
        35527,
        37278
      ]
    }
  },
  "movers": [
    {
      "sku": "Amberleaf Green Tea 100g",
      "brand": "Amberleaf",
      "category": "Hot drinks",
      "current": 217770.4,
      "prior": 165087.2,
      "delta": 52683.2,
      "pct": 31.9
    },
    {
      "sku": "Crispa Wafer Multipack",
      "brand": "Crispa",
      "category": "Biscuits",
      "current": 444375.6,
      "prior": 342573.6,
      "delta": 101802.0,
      "pct": 29.7
    },
    {
      "sku": "Solara Sunflower Oil 5L",
      "brand": "Solara",
      "category": "Edible oil",
      "current": 962712.0,
      "prior": 777060.0,
      "delta": 185652.0,
      "pct": 23.9
    },
    {
      "sku": "Solara Sunflower Oil 1.8L",
      "brand": "Solara",
      "category": "Edible oil",
      "current": 1158326.4,
      "prior": 969785.6,
      "delta": 188540.8,
      "pct": 19.4
    },
    {
      "sku": "Nuvora Dish Liquid 750ml",
      "brand": "Nuvora",
      "category": "Home care",
      "current": 467992.05,
      "prior": 400684.05,
      "delta": 67308.0,
      "pct": 16.8
    },
    {
      "sku": "Amberleaf Black Tea 250g",
      "brand": "Amberleaf",
      "category": "Hot drinks",
      "current": 641100.0,
      "prior": 582862.5,
      "delta": 58237.5,
      "pct": 10.0
    },
    {
      "sku": "Pellara Tomato Paste 400g",
      "brand": "Pellara",
      "category": "Ambient",
      "current": 436665.6,
      "prior": 398630.4,
      "delta": 38035.2,
      "pct": 9.5
    },
    {
      "sku": "Crispa Cream Biscuit 90g",
      "brand": "Crispa",
      "category": "Biscuits",
      "current": 510086.4,
      "prior": 517056.0,
      "delta": -6969.6,
      "pct": -1.3
    },
    {
      "sku": "Nuvora Detergent 2kg",
      "brand": "Nuvora",
      "category": "Home care",
      "current": 649610.0,
      "prior": 712125.1,
      "delta": -62515.1,
      "pct": -8.8
    },
    {
      "sku": "Marisol Bath Soap 125g",
      "brand": "Marisol",
      "category": "Personal",
      "current": 201897.5,
      "prior": 240059.95,
      "delta": -38162.45,
      "pct": -15.9
    }
  ],
  "coverage": [
    {
      "distributor": "Harbour Line Co.",
      "region": "Coast",
      "outlets": 980,
      "covered": 822,
      "pct": 83.9,
      "priorPct": 84.6,
      "deltaPp": -0.7
    },
    {
      "distributor": "Blue Cedar Distribution",
      "region": "Central",
      "outlets": 2210,
      "covered": 1699,
      "pct": 76.9,
      "priorPct": 71.2,
      "deltaPp": 5.7
    },
    {
      "distributor": "Riverbend Trading",
      "region": "Central",
      "outlets": 1520,
      "covered": 1143,
      "pct": 75.2,
      "priorPct": 73.0,
      "deltaPp": 2.2
    },
    {
      "distributor": "Northgate Trading",
      "region": "North",
      "outlets": 1840,
      "covered": 1363,
      "pct": 74.1,
      "priorPct": 78.5,
      "deltaPp": -4.4
    },
    {
      "distributor": "Sandstone Wholesale",
      "region": "South",
      "outlets": 1370,
      "covered": 800,
      "pct": 58.4,
      "priorPct": 66.8,
      "deltaPp": -8.4
    }
  ],
  "coverageTotal": {
    "outlets": 7920,
    "covered": 5827,
    "pct": 73.6,
    "priorPct": 74.1,
    "deltaPp": -0.6
  }
};
