/* GENERATED by demo/build_sales_data.py — do not hand-edit.
   100% synthetic. No real customer, distributor, product or
   figure appears in this file. Seed 20260816, so regenerating gives
   byte-identical output. */
window.DEMO_SALES = {
  "meta": {
    "synthetic": true,
    "currency": "USD",
    "currentLabel": "This year",
    "priorLabel": "Last year",
    "throughMonth": "Oct",
    "monthsElapsed": 10,
    "months": [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    ],
    "seed": 20260816,
    "note": "Every figure on this page is generated. No real customer, distributor, product or number appears anywhere in it."
  },
  "kpi": {
    "value": {
      "current": 5690535.95,
      "prior": 5105924.4
    },
    "volume": {
      "current": 347935,
      "prior": 320674
    },
    "lines": {
      "current": 50,
      "prior": 50
    },
    "coverage": {
      "current": 73.6,
      "prior": 74.1
    },
    "dropSize": {
      "current": 16.36,
      "prior": 15.92
    }
  },
  "trend": {
    "value": {
      "current": [
        569174.65,
        550899.85,
        561114.25,
        590293.1,
        613035.65,
        535332.0,
        510082.1,
        541450.05,
        586293.8,
        632860.5
      ],
      "prior": [
        518700.1,
        491774.95,
        515288.4,
        536013.95,
        548838.15,
        480439.8,
        457652.25,
        484367.95,
        517665.45,
        555183.4,
        572669.05,
        599608.25
      ]
    },
    "volume": {
      "current": [
        35255,
        33762,
        34924,
        36089,
        37422,
        32714,
        30943,
        32935,
        35663,
        38228
      ],
      "prior": [
        32850,
        31173,
        32542,
        33709,
        34878,
        30217,
        28599,
        29991,
        32062,
        34653,
        35527,
        37278
      ]
    },
    "byDistributor": {
      "Northgate Trading": {
        "value": {
          "current": [
            154475.65,
            150359.45,
            152712.7,
            157468.0,
            169034.2,
            140462.65,
            136394.25,
            147222.55,
            154692.65,
            171891.4
          ],
          "prior": [
            145276.9,
            131763.05,
            138756.1,
            145490.55,
            148509.3,
            128185.1,
            121668.2,
            125731.15,
            138696.8,
            148161.25,
            150981.55,
            158264.35
          ]
        },
        "volume": {
          "current": [
            9455,
            9228,
            9529,
            9651,
            10278,
            8680,
            8264,
            9003,
            9387,
            10369
          ],
          "prior": [
            9138,
            8349,
            8724,
            9126,
            9461,
            8062,
            7759,
            7887,
            8753,
            9148,
            9434,
            9924
          ]
        }
      },
      "Blue Cedar Distribution": {
        "value": {
          "current": [
            94019.6,
            93211.3,
            95583.4,
            102424.3,
            104717.1,
            90573.0,
            85720.7,
            92153.25,
            99377.65,
            101448.45
          ],
          "prior": [
            86970.55,
            83342.7,
            87234.65,
            90840.05,
            91018.75,
            78813.2,
            79587.2,
            83357.75,
            84873.8,
            97498.65,
            101348.7,
            103942.15
          ]
        },
        "volume": {
          "current": [
            5952,
            5773,
            6014,
            6191,
            6409,
            5503,
            5342,
            5593,
            5995,
            6310
          ],
          "prior": [
            5587,
            5350,
            5505,
            5668,
            5903,
            4960,
            5007,
            5144,
            5329,
            6065,
            6327,
            6409
          ]
        }
      },
      "Harbour Line Co.": {
        "value": {
          "current": [
            103759.6,
            97996.3,
            99567.0,
            108668.05,
            109876.7,
            96932.75,
            93299.1,
            97362.9,
            109503.7,
            113662.75
          ],
          "prior": [
            95467.75,
            91671.85,
            92694.75,
            99358.95,
            96473.4,
            84857.05,
            84798.15,
            89677.55,
            92562.9,
            95373.65,
            104065.05,
            108413.5
          ]
        },
        "volume": {
          "current": [
            6459,
            6026,
            6115,
            6622,
            6666,
            5989,
            5606,
            5841,
            6662,
            6836
          ],
          "prior": [
            5977,
            5790,
            5978,
            6225,
            6053,
            5344,
            5197,
            5520,
            5673,
            6056,
            6450,
            6725
          ]
        }
      },
      "Sandstone Wholesale": {
        "value": {
          "current": [
            118856.5,
            114500.4,
            116436.35,
            121893.7,
            125212.3,
            113365.35,
            106355.9,
            115794.0,
            122873.2,
            135482.2
          ],
          "prior": [
            103680.5,
            99951.15,
            108787.0,
            109959.05,
            117108.0,
            103925.65,
            96932.05,
            101428.05,
            110785.05,
            120010.5,
            118952.25,
            126521.6
          ]
        },
        "volume": {
          "current": [
            7292,
            6907,
            7322,
            7581,
            7753,
            6890,
            6366,
            7020,
            7404,
            8202
          ],
          "prior": [
            6614,
            6343,
            6830,
            7029,
            7355,
            6515,
            5974,
            6285,
            6661,
            7396,
            7313,
            7946
          ]
        }
      },
      "Riverbend Trading": {
        "value": {
          "current": [
            98063.3,
            94832.4,
            96814.8,
            99839.05,
            104195.35,
            93998.25,
            88312.15,
            88917.35,
            99846.6,
            110375.7
          ],
          "prior": [
            87304.4,
            85046.2,
            87815.9,
            90365.35,
            95728.7,
            84658.8,
            74666.65,
            84173.45,
            90746.9,
            94139.35,
            97321.5,
            102466.65
          ]
        },
        "volume": {
          "current": [
            6097,
            5828,
            5944,
            6044,
            6316,
            5652,
            5365,
            5478,
            6215,
            6511
          ],
          "prior": [
            5534,
            5341,
            5505,
            5661,
            6106,
            5336,
            4662,
            5155,
            5646,
            5988,
            6003,
            6274
          ]
        }
      }
    }
  },
  "movers": [
    {
      "sku": "Amberleaf Green Tea 100g",
      "brand": "Amberleaf",
      "category": "Hot drinks",
      "current": 217770.4,
      "prior": 165087.2,
      "delta": 52683.2,
      "pct": 31.9
    },
    {
      "sku": "Crispa Wafer Multipack",
      "brand": "Crispa",
      "category": "Biscuits",
      "current": 444375.6,
      "prior": 342573.6,
      "delta": 101802.0,
      "pct": 29.7
    },
    {
      "sku": "Solara Sunflower Oil 5L",
      "brand": "Solara",
      "category": "Edible oil",
      "current": 962712.0,
      "prior": 777060.0,
      "delta": 185652.0,
      "pct": 23.9
    },
    {
      "sku": "Solara Sunflower Oil 1.8L",
      "brand": "Solara",
      "category": "Edible oil",
      "current": 1158326.4,
      "prior": 969785.6,
      "delta": 188540.8,
      "pct": 19.4
    },
    {
      "sku": "Nuvora Dish Liquid 750ml",
      "brand": "Nuvora",
      "category": "Home care",
      "current": 467992.05,
      "prior": 400684.05,
      "delta": 67308.0,
      "pct": 16.8
    },
    {
      "sku": "Amberleaf Black Tea 250g",
      "brand": "Amberleaf",
      "category": "Hot drinks",
      "current": 641100.0,
      "prior": 582862.5,
      "delta": 58237.5,
      "pct": 10.0
    },
    {
      "sku": "Pellara Tomato Paste 400g",
      "brand": "Pellara",
      "category": "Ambient",
      "current": 436665.6,
      "prior": 398630.4,
      "delta": 38035.2,
      "pct": 9.5
    },
    {
      "sku": "Crispa Cream Biscuit 90g",
      "brand": "Crispa",
      "category": "Biscuits",
      "current": 510086.4,
      "prior": 517056.0,
      "delta": -6969.6,
      "pct": -1.3
    },
    {
      "sku": "Nuvora Detergent 2kg",
      "brand": "Nuvora",
      "category": "Home care",
      "current": 649610.0,
      "prior": 712125.1,
      "delta": -62515.1,
      "pct": -8.8
    },
    {
      "sku": "Marisol Bath Soap 125g",
      "brand": "Marisol",
      "category": "Personal",
      "current": 201897.5,
      "prior": 240059.95,
      "delta": -38162.45,
      "pct": -15.9
    }
  ],
  "coverage": [
    {
      "distributor": "Harbour Line Co.",
      "region": "Coast",
      "outlets": 980,
      "covered": 822,
      "pct": 83.9,
      "priorPct": 84.6,
      "deltaPp": -0.7
    },
    {
      "distributor": "Blue Cedar Distribution",
      "region": "Central",
      "outlets": 2210,
      "covered": 1699,
      "pct": 76.9,
      "priorPct": 71.2,
      "deltaPp": 5.7
    },
    {
      "distributor": "Riverbend Trading",
      "region": "Central",
      "outlets": 1520,
      "covered": 1143,
      "pct": 75.2,
      "priorPct": 73.0,
      "deltaPp": 2.2
    },
    {
      "distributor": "Northgate Trading",
      "region": "North",
      "outlets": 1840,
      "covered": 1363,
      "pct": 74.1,
      "priorPct": 78.5,
      "deltaPp": -4.4
    },
    {
      "distributor": "Sandstone Wholesale",
      "region": "South",
      "outlets": 1370,
      "covered": 800,
      "pct": 58.4,
      "priorPct": 66.8,
      "deltaPp": -8.4
    }
  ],
  "coverageTotal": {
    "outlets": 7920,
    "covered": 5827,
    "pct": 73.6,
    "priorPct": 74.1,
    "deltaPp": -0.6
  }
};
